author: Dallas Borealis
email: dallas.borealis@gmail.com

description: See/hear something; save it; share it.<br />Oh, and Dallas Borealis is a play on the lyrics of <em>"Can You Picture That?"</em> by Dr. Teeth and the Electric Mayhem
